# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# TODO https://squidfunk.github.io/mkdocs-material/reference/diagrams/
site_name: iown-homecontrol
site_url: https://velocet.github.io/iown-homecontrol/
site_description: io-homecontrol Documentation &amp; Implementation
site_author: Velocet
repo_name: iown @ GitHub
repo_url: https://github.com/velocet/iown-homecontrol/
edit_uri: blog/main/docs/ # edit/main/docs/
copyright: '&copy; iown-homecontrol'

# Output files folder. Put 'site' in '.cache': Unclutter folders + only exclude '.cache'.
site_dir: .cache/site
# Files to exclude from the built site.
exclude_docs: |
  datasheets/
  devices/
  firmware/
  parameter/
  reference/
  # Include 'assets' no matter what
  !assets/
# Draft files are available during 'mkdocs serve' but not in 'mkdocs build'.
# draft_docs:

nav:
  - ⌂: README.md
  - Protocol:
    - Layer 1: RADIO.md
    - Layer 2: LINKLAYER.md
    - Commands: COMMANDS.md
    - Parameter: PARAMETER.md
  - Reference:
    - Devices: DEVICES.md
    - Firmware: FIRMWARE.md
  - misc:
    - RTL-SDR: RADIO-RTLSDR.md

plugins:
  - search
  - privacy:
      assets: true
      assets_fetch: true
  - git-revision-date-localized

extra:
  homepage: https://github.com/velocet/iown-homecontrol
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/MPEb7dTNdN
      name: iown-Discord
    - icon: fontawesome/brands/telegram
      link: https://t.me/iownHomecontrol
      name: iown-Telegram

theme:
  name: material
  locale: en
  highlightjs: true
  logo: assets/favicon.png
  favicon: assets/favicon.png
  font:
    text: Open Sans
    code: Source Code Pro
  palette:
    primary: grey # blue grey
    accent: light blue
  features:
    - header.autohide
    - navigation.footer
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: topix
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: false
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  #     clickable_checkbox: false

validation:
  nav:
    omitted_files: info
    not_found: info
    absolute_links: info
  links:
    not_found: info
    # anchors: info
    absolute_links: info
    unrecognized_links: info
