# yaml-language-server: $schema=https://github.com/SchemaStore/schemastore/raw/master/src/schemas/json/github-issue-forms.json

name: Bug Report
description: File a Bug Report!
title: "[BUG]: "
labels: ["bug", "triage"]

assignees:
  - Velocet

body:
  - type: markdown
    attributes:
      value: |
        Thanks for filling out this bug report!
  - type: dropdown
    id: board_id
    attributes:
      label: Board
      description: Which board are you using?
      multiple: false
      options:
        - HelTec LoRa32
        - HelTec Stick
        - HelTec Stick Lite
  - type: textarea
    id: report
    attributes:
      label: Bug Description
      description: Describe the bug and the situation around it.
      placeholder: Don't forget to give some context...
