# Prettier friendly markdownlint config (all formatting rules disabled)
# extends: markdownlint/style/prettier

# Autoformatter friendly markdownlint config (all formatting rules disabled)
default: true

blank_lines: false
bullet: false
html: false
indentation: false
line_length: false
spaces: false
url: false
whitespace: false

# Exclusions for deliberate/widespread violations
MD002: false     # DEPRECATED: First header should be a h1 header
MD004:           # Unordered list style
    style: dash
MD006: false     # DEPRECATED: ul-start-left
MD007:           # Unordered list indentation
    indent: 2
MD013: false     # Line length
# MD019: false     # Multiple spaces after hash on atx style header
# MD021: false     # Multiple spaces inside hashes on closed atx style header
# MD024: false     # Multiple headers with the same content
# MD026: false     # Trailing punctuation in header
# MD029: false     # Ordered list item prefix
MD030: false     # Spaces after list markers
MD033: false     # Allow inline HTML
MD041: false     # First line in file should be a top level header
MD046:           # Code block style
    style: fenced
