# yaml-language-server: $schema=https://github.com/SchemaStore/schemastore/raw/master/src/schemas/json/github-workflow.json

name: MkDocs Spell Check

# TODO Remove
on: workflow_dispatch
  # push:
  #   paths:             # Only run changes in these directories
  #     - docs/**
  # pull_request:
  #   paths:             # Only run changes in these directories
  #     - docs/**
  # Allows to run this workflow manually from the Actions tab

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Spell check
        uses: codespell-project/actions-codespell@master
