# TODO Get Version Name in here!
name: PlatformIO

on:
  push:
    branches: [ main ] # Only run on main branch
    paths:               # Only run on these directories
      - data
      - inc
      - include
      - src
  pull_request:
    branches: [ main ] # Only run on main branch
    paths:               # Only run on these directories
      - data
      - inc
      - include
      - src

permissions:
  contents: write

jobs:
  build:
    name: PlatformIO Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            path:
              ~\AppData\Local\pip\Cache
              ~\.platformio\.cache
          - os: ubuntu-latest
            path:
              ~/.cache/pip
              ~/.platformio/.cache
          - os: macos-latest
            path:
              ~/Library/Caches/pip
              ~/.platformio/.cache

    permissions:
      security-events: write # all workflows
      packages: read         # fetch internal or private CodeQL packs
      actions: read          # private repos
      contents: write        # private repos

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Cache
      uses: actions/cache@v4
      with:
        key:
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          ${{ runner.os }}-pio
        path: ${{ matrix.path }}
        restore-keys:
          ${{ runner.os }}-pip-
          ${{ runner.os }}-pio
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        check-latest: true # is cached version the latest one?
        cache: pip         # caching pip dependencies
    - name: 'PlatformIO: Install Core'
      run:
        python -m pip install --upgrade pip
        pip list --outdated --no-color | tail --lines=+3 | cut --delimiter=" " --fields=1 | xargs --max-args=1 pip install --upgrade
    - name: 'PlatformIO: Show Project Config'
      run: pio project config
    - name: 'PlatformIO: Build Project'
      run: pio run
